name: Gauges List
run-name: Generating list of active gauges
on:
  push:
  schedule:
    - cron: 0 4 * * 4 # every Thursday at 4am
jobs:
  active-gauges-eth:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install pip dependencies
        run: pip install -r requirements.txt
      - name: Log active gauges on Ethereum
        run: python tasks/generate_eth_gauge_choices.py
        env:
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
      - name: Commit changes
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Snapshot latest gauges"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
